### ISSUE TITLE
Emoji replace won't work at Magisk Delta 26302

### ISSUE THREAD

**Issue by PianCat** [HuskyDG/Zygisk-FontLoader#4]
Emoji replace module won't work at [Magisk Delta 26302](https://github.com/HuskyDG/magisk-files/releases/tag/0fe46c5a-delta).

When `unmount modules by default` is enabled. not work with modify fonts.xml to force using the emoji ttf either.

[Twemoji 14.zip](https://github.com/HuskyDG/Zygisk-FontLoader/files/13112724/Twemoji.14.zip)

↑Here's the module, if it works, it will replace Emoji to TwiEmoji. (By changing NotoColorEmoji.ttf ways.)

I m using iOS Emoji with MiSans pack, but same by changing NotoColorEmoji.ttf to replace.

Heres Magisk Log:

[magisk_log_2023-10-24T17.02.48.log](https://github.com/HuskyDG/Zygisk-FontLoader/files/13112798/magisk_log_2023-10-24T17.02.48.log)

Here is Android Log:

[FontLoader.log](https://github.com/HuskyDG/Zygisk-FontLoader/files/13112799/FontLoader.log)

Not working like:

![image](https://github.com/HuskyDG/Zygisk-FontLoader/assets/50688679/6ddd84a3-a834-4082-8444-4ec63c814eb3)

If its working properlly, it will be like:

![image](https://github.com/HuskyDG/Zygisk-FontLoader/assets/50688679/2544b240-166d-497c-b64a-6ef2231dd9a7)

At the pictures above, It shows:
Fonts replace works fine (change Roboto to MiSans)
but Emoji replace wont work (If need change emoji, that needs add Apps into mount list)

**Comment by PianCat** [comment]
Some additional feedback
If unmount modules by default is enabled, all browsers that rely on Trichrome library and Webview, such as via, Chrome, etc., will not be able to mount fonts correctly.
With unmount modules by default disable:
![image](https://github.com/HuskyDG/Zygisk-FontLoader/assets/50688679/8f075bde-85a0-4d5f-9a91-7b90de01e1ab)
With unmount modules by default enable:
![image](https://github.com/HuskyDG/Zygisk-FontLoader/assets/50688679/88cfbc41-c894-418f-8dac-2d1857323443)

**Comment by PianCat** [comment]
The fonts module u might need for test:
[MiSans+Twiemoji.zip](https://github.com/HuskyDG/Zygisk-FontLoader/files/13113476/MiSans%2BTwiemoji.zip)

**Comment by CoelacanthusHex** [comment]
I have the same issue with Nagram and KernelSu 0.9.4.
